### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by whohoho** [tracking-exposed/facebook#86]
`
$ npm run watch

> facebook-tracking-exposed@1.0.0 watch /home/user/src/facebook/facebook
> nodemon --config config/nodeamon.json app

[nodemon] 1.18.3
[nodemon] reading config ./config/nodeamon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 10358 to restart
[nodemon] ignoring: sections/webscripts/*.js
[nodemon] watching: lib/*.js app.js sections/*.pug sections/*/*.pug dist/**
[nodemon] watching extensions: js,css,pug
[nodemon] starting `node app app.js`
[nodemon] forking
[nodemon] child pid: 10370
[nodemon] watching 272 files
/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:59
    throw err;
    ^

Error: /home/user/src/facebook/facebook/lib/../sections/talks/landing.pug:50:1
    48|           a(href="https://elezioni.tracking.exposed") https://elezioni.tracking.exposed
    49|           |  some 
  > 50|             b English 
--------^
    51|           | blogpost commenting on the analysis are: 
    52|           a(href="https://medium.com/@trackingexposed/facebook-tracking-exposed-background-80e0f72e615f") Methodology/Background
    53|           |, 

unexpected token "indent"
    at makeError (/home/user/src/facebook/facebook/node_modules/pug-error/index.js:32:13)
    at Parser.error (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:53:15)
    at Parser.parseExpr (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:264:14)
    at Parser.block (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:996:25)
    at Parser.tag (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:1157:24)
    at Parser.parseTag (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:1049:17)
    at Parser.parseExpr (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:208:21)
    at Parser.block (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:996:25)
    at Parser.tag (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:1157:24)
    at Parser.parseTag (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:1049:17)
    at Parser.parseExpr (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:208:21)
    at Parser.block (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:996:25)
    at Parser.tag (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:1157:24)
    at Parser.parseTag (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:1049:17)
    at Parser.parseExpr (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:208:21)
    at Parser.block (/home/user/src/facebook/facebook/node_modules/pug-parser/index.js:996:25)
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by vecna** [comment]
sorry for my late answer. I introduced that bug and solved it while implementing the prototype of the researcher interface, has been fixed here https://github.com/tracking-exposed/facebook/commit/8e8bb7500ff7e7b9eebcf985739fb38014ca1fde#diff-e217b87e6d0a25a3f6cfe391e7f081ca 

The current version should run smoothly. can you confirm?

**Comment by vecna** [comment]
this bug was old and temporary; I'm closing this issue. In the next days the 1.0.1 version would be released
